services:
  swarch2022i_db:
    build: ./swarch2022i_db/
    ports:
      - "3306:3306"
  db_client:
    image: phpmyadmin
    links:
      - swarch2022i_db:db
    ports:
      - "8081:80"
    depends_on:
      - swarch2022i_db
  swarch2022i_ms:
    build: ./swarch2022i_ms/
    ports:
      - "4000:4000"
    links:
      - swarch2022i_db:db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=swarch2022i
      - DB_PASSWORD=2022
      - DB_NAME=swarch2022i_db
      - URL=0.0.0.0:4000
    depends_on:
      - swarch2022i_db
  swarch2022i_ag:
    build: ./swarch2022i_ag/
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - swarch2022i_ms